### ISSUE TITLE
Real moonback Background/Fill

### ISSUE THREAD

**Issue by DaAwesomeP** [tingletech/moon-phase#3]
Would it be possible to use this always up-to-date image as the background for the part of the moon that is lit up? I have limited to no experience with SVGs, but I realize that there needs to be some sort of frame or cut-path in a circle. It would also have to be centered. Great library!

![moon 1](http://api.usno.navy.mil/imagery/moon.png)

From http://aa.usno.navy.mil/imagery/moon. If GitHub doesn't update it, look here: http://api.usno.navy.mil/imagery/moon.png

**Comment by tingletech** [comment]
According to stackoverflow, it looks like it is possible to set a png as a background for a svg.
http://stackoverflow.com/a/11500364/1763984 

Part of my goal for this project was to test out building a javascript app that would run with no internet connection (the manifest file).  I was thinking if I was camping or just trying to save battery by putting it in airplane mode that it would be cool to have an app that would tell me the sunrise/sunset and the moon phase without going on-line.  I was trying to make an offline version of the above png.

Also, my little toy does not seem to be correct all the time (full moon and new moon seem right, but somehow the timing is a little off, like today this picture looks dark, but I show a little sliver).
