### ISSUE TITLE
Illumination glitch on 75% of moon phase.

### ISSUE THREAD

**Issue by Beanow** [tingletech/moon-phase#4]
I've adopted your SVG rendering into an indicator. Today I'm noticing the foreground glitches out of the moon.
![moon icon](http://ss.oscp.info/2015-01-13_15-45-50.png)

The input I'm giving is, `0.758284352411` for the moon phase.
And here is the ported Python code I'm using: http://git.oscp.info/beanow/lunar-indicator/blob/master/indicator.py#L6

Can you spot what the problem is? Is it in my moving of the paths?

Update: the range that causes issues is about `0.7374` - `0.7626`

**Comment by Beanow** [comment]
The inverse effect is noticeable on the current 25% range too.

**Comment by tingletech** [comment]
sorry, I have no idea; I just figured the `<svg>` out via trial and error mostly
