### ISSUE TITLE
Is it possible to find the next new moon using moon-phase?

### ISSUE THREAD

**Issue by WimDeMeester** [tingletech/moon-phase#5]
I can not find this in the documentation... I would like to find the new moon in a given month (or the two new moons if there are two that month).

**Comment by tingletech** [comment]
this little toy was just for me to play around with making a web app to run on a phone with a manifest file.

This is where I got the moon phase info http://www.ben-daglish.net/moon.shtml

**Comment by WimDeMeester** [comment]
Thanks!
